He añadido mi nombre y el nombre de usuario
basesdepatos/notes pull request #17
Opened 2024-12-02 12:30 UTC by YuUs01

2024-12-02 12:37 UTC, bananas24 requested changes

2024-12-02 12:37 UTC, bananas24 commented on contributors.md
> +
I don't like this blank line, remove it

2024-12-02 12:37 UTC, bananas24 commented on contributors.md
> +Youssef - YuUs01
All dashes must be in the same column

2024-12-02 15:08 UTC, bananas24 requested changes
In the PR description, the word used is not one of the proper keywords. Check here:
https://docs.github.com/en/issues/tracking-your-work-with-issues/using-issues/linking-a-pull-request-to-an-issue

2024-12-02 15:08 UTC, bananas24 commented on contributors.md
> +Youssef - YuUs01
Good job, now I would like to have all dashes in the same column.
For example:
``
bananas24 - teacher
``
``
Youssef   - YuUs01
``

2024-12-03 11:20 UTC, bananas24 approved these changes
Thanks Youssef! Good job.
Next time, I want all commit messages, PR title and descriptionin English!

2024-12-03 11:25 UTC, bananas24 requested changes
Message to close the issue still missing from the PR. Otherwise, looking good.

2024-12-03 15:38 UTC, bananas24 approved these changes

2024-12-04 10:39 UTC, Lowri-ui approved these changes

2024-12-04 10:39 UTC, tamasi17 approved these changes
gg

2024-12-04 10:39 UTC, ItsKein approved these changes

2024-12-04 10:39 UTC, Karls3fni commented
grande

2024-12-04 10:41 UTC, merged