add David
basesdepatos/notes pull request #21
Opened 2024-12-02 12:42 UTC by DGuelar

2024-12-02 14:58 UTC, bananas24 reviewed
Good job David

2024-12-02 14:59 UTC, bananas24 submitted a review, later dismissed
Good job David

2024-12-02 15:02 UTC, bananas24 requested changes
Code is good, David, but I want you to include a comment in the PR stating which issue it is closing (the issue you should have assigned to yourself)

2024-12-09 10:33 UTC, AshysCoffee approved these changes

2024-12-09 12:00 UTC, bananas24 approved these changes

2024-12-09 12:02 UTC, symn369 approved these changes

2024-12-09 12:02 UTC, merged