Add laura
basesdepatos/notes pull request #25
Opened 2024-12-02 17:12 UTC by Lowri-ui

Lo modifiqué un poquito para que se viera más visual. Está completada la tarea.

2024-12-03 11:27 UTC, bananas24 requested changes
Great idea, but a bit ahead of time though! Sorry but we need to stick to the original format at the beginning. Please just add your name and username as per the original format.
Keep the idea for future homework!
In addition, I want a message in the PR addressing the issue:
https://docs.github.com/en/issues/tracking-your-work-with-issues/using-issues/linking-a-pull-request-to-an-issue

2024-12-03 16:37 UTC, bananas24 commented
Good job linking the issue.

There is a small (unimportant) thing, but I would like all dashes to be in the same column. For example:

``
bananas24 - teacher
``
``
Lowri-ui  - Laura
``

2024-12-04 10:52 UTC, tamasi17 approved these changes

2024-12-04 10:53 UTC, bananas24 approved these changes

2024-12-04 10:53 UTC, YuUs01 approved these changes

2024-12-04 10:54 UTC, merged