added my name again to try it from my personal computer
basesdepatos/notes pull request #26
Opened 2024-12-02 21:38 UTC by tamasi17

this is the same example, you can delete one of mine, they're exactly the same

2024-12-03 11:24 UTC, bananas24 requested changes
Good job Mati. No need to create a new PR, though. You can overwrite the previous one.
And you can delete it yourself now as well, to avoid duplicates.
Anyway, I still want you to put a message in the PR stating which "issue" it is addressing.

2024-12-04 11:20 UTC, YuUs01 approved these changes

2024-12-04 11:34 UTC, Lowri-ui approved these changes

2024-12-04 11:36 UTC, Lowri-ui approved these changes

2024-12-04 11:43 UTC, ItsKein approved these changes

2024-12-04 11:43 UTC, ItsKein approved these changes

2024-12-04 11:45 UTC, KU3ERVO approved these changes
mu bonito

2024-12-04 11:46 UTC, bananas24 approved these changes

2024-12-04 11:46 UTC, merged