I added my name to contributors file
basesdepatos/notes pull request #43
Opened 2024-12-04 11:46 UTC by Montezz14

[https://github.com/basesdepatos/notes/issues/15](url)

2024-12-04 12:05 UTC, ItsKein approved these changes

2024-12-04 12:06 UTC, YuUs01 requested changes
you have to restore the names deleted

2024-12-04 12:19 UTC, naroa0699 approved these changes

2024-12-04 12:35 UTC, filichris98 approved these changes

2024-12-11 07:38 UTC, YuUs01 approved these changes
everything OK

2024-12-11 07:38 UTC, merged