Update contributors.md
basesdepatos/notes pull request #5
Opened 2024-12-02 12:14 UTC by HaggardCoder

2024-12-02 12:29 UTC, bananas24 requested changes

2024-12-02 12:29 UTC, bananas24 commented on contributors.md
> +HaggardCoder -Eduardo
I want a space between the dash and your name

2024-12-02 12:29 UTC, bananas24 commented on contributors.md
> -bananas24 - teacher
I want all dashes to be at the same column

2024-12-02 15:05 UTC, bananas24 requested changes
And I also miss a description in the PR stating which issue it is addressing
(from https://github.com/basesdepatos/notes/issues)

2024-12-02 15:05 UTC, bananas24 commented on contributors.md
> +   bananas24 - teacher
I'd like the spaces after the name, rather than at the beginning. Something like:
``
bananas24    - teacher
``
``
HaggardCoder - Eduardo
``

2024-12-04 10:54 UTC, daniela898 approved these changes

2024-12-04 10:55 UTC, merged