added an SQL Mindmap to other.md
basesdepatos/notes pull request #82
Opened 2024-12-18 11:56 UTC by tamasi17

Tried using links to add visual support to these notes. I thought this SQL Mindmap was decent for now.

@YuUs01 @Sosoloogic 
@bananas24 please review this.

2024-12-18 11:58 UTC, Sosoloogic approved these changes

2024-12-18 12:02 UTC, JaimeRuiz06 approved these changes
Good job!
![image](https://github.com/user-attachments/assets/30c0e467-22aa-4737-9820-dfe76f0e0794)

2024-12-18 21:06 UTC, YuUs01 approved these changes
Looks good

2025-01-13 10:34 UTC, bananas24 requested changes

2025-01-13 10:34 UTC, bananas24 commented on unit1/other.md
> +All this commands can be easier to see in this [SQL Mindmap](https://edrawcloudpublicus.s3.amazonaws.com/work/2679487/2022-9-29/1664454682/thumb.png?x-oss-process=image/resize,w_300,m_lfit).
I would like to have images directly added to the repo, not having to rely on external sources

2025-01-13 10:35 UTC, tamasi17 commented on unit1/other.md
> +All this commands can be easier to see in this [SQL Mindmap](https://edrawcloudpublicus.s3.amazonaws.com/work/2679487/2022-9-29/1664454682/thumb.png?x-oss-process=image/resize,w_300,m_lfit).
Agreed, working it 👍

2025-01-13 11:31 UTC, tamasi17 commented
@naroa0699  @bananas24 @YuUs01 @Sosoloogic please check this last update to the other.md file with an image

2025-01-13 11:32 UTC, naroa0699 approved these changes
Okay i checked this, is fine .)

2025-01-13 11:33 UTC, bananas24 approved these changes

2025-01-13 11:35 UTC, merged

2025-01-13 11:35 UTC, Sosoloogic commented
> @naroa0699 @bananas24 @YuUs01 @Sosoloogic please check this last update to the other.md file with an image

i did a quick check , everyting looks good